SET NAMES utf8;                                                                                                                                                                              
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

SET NAMES utf8mb4;

USE elektrum;

CREATE TABLE `PROFILI` (
  `ID` VARCHAR(255), 
  `KWH_TOTAL_HOURS` DECIMAL(18)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PROFILI_4_DIENAS` (
  `METER_ID` VARCHAR(255) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PROFILI_4_DIENAS_MSNO` (
  `METER_ID` VARCHAR(255), 
  `STATUS` VARCHAR(255) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


INSERT INTO `PROFILI` SELECT `METER_ID`, `KWH_IMPORT` + `KWH_EXPORT` AS `KWH_TOTAL_HOURS` FROM `DATA_E` WHERE `DATA_TIME` = '2020-04-16';
INSERT INTO `PROFILI_4_DIENAS` SELECT DISTINCT `METER_ID` FROM DATA_E WHERE `DATA_TIME` BETWEEN '2020-04-16' AND '2020-04-19 23:59:59';


INSERT INTO PROFILI_4_DIENAS_MSNO
SELECT DISTINCT  DATA_E.METER_ID, METER_A.STATUS
FROM DATA_E JOIN METER_A on DATA_E.METER_ID
WHERE (DATA_TIME BETWEEN '2020-04-16' AND '2020-04-19') AND (METER_A.STATUS= 3);
